
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrjbqubkctepwgntxqft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyamJxdWJrY3RlcHdnbnR4cWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NzE0MzUsImV4cCI6MjA1NzI0NzQzNX0.PERD0l6LW2IXiJ0fKb7rP5A8cH62clPF4_w4fVZeEPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
